### ISSUE TITLE
support corporate proxies via environment variables

### ISSUE THREAD

**Issue by bcoe** [grpc/grpc-node#1005]
### Is your feature request related to a problem? Please describe.

[grpc](https://www.npmjs.com/package/grpc) supports proxies through the HTTP_PROXY/HTTPS_PROXY environment variables. We've been in the process of moving client libraries at Google over to `grpc-js`, which does not support proxies (this has left a few customers in the lurch).

### Describe the solution you'd like

Ideally `grpc-js` would detect that HTTP_PROXY or HTTPS_PROXY has been set, and respect the value when negotiating a connection.

### Describe alternatives you've considered

Alternatively, perhaps `grpc-js` should expose a `proxy` configuration option, and upstream libraries could handle populating it from environment.

### Additional context

Related: https://github.com/grpc/grpc-node/issues/982

**Comment by DTrejo** [comment]
Dear maintainers, 

1) What are your thoughts on this? 
2) If you don't have time, would you be open to someone submitting a PR to add this?

Thanks in advance!

**Comment by murgatroid99** [comment]
This is something I would like to do, but it's not at the top of my priority list. I would accept a PR that adds the same APIs that the other `grpc` library supports (i.e. handling the `HTTP_PROXY` and `HTTPS_PROXY` environment variables). I believe the correct way to do this is to modify how the `Subchannel` class establishes connections so that if the corresponding environment variable is set, it performs a HTTP/1.1 CONNECT call and then uses the resulting stream as the underlying connection for the new http2 session.

**Comment by MJBGO** [comment]
Hi !

Do you have any updates on that feature ?

Thanks :)

**Comment by murgatroid99** [comment]
See PR #1243. I expect to be able to publish that pretty soon.

**Comment by zamnuts** [comment]
@bcoe #1243 is now merged and has been released as `@grpc/grpc-js@0.7.0` which supports proxy configuration via specific environment variables (in order of precedence):
- `grpc_proxy`
- `https_proxy`
- `http_proxy`

Note that these env vars are case-sensitive in *nix, but case-insensitive on win. Your original request was for uppercase `HTTPS_PROXY` and `HTTP_PROXY`. I've opened #1292 to propose this feature. We can probably close this issue, and maybe the related one at https://github.com/googleapis/nodejs-tasks/issues/291.
