### ISSUE TITLE
grpc-js: Failed to parse target + adding a custom resolver

### ISSUE THREAD

**Issue by danschultz** [grpc/grpc-node#1054]
### Problem description
I'm trying to add a custom resolver to resolve hosts through Consul and am getting an error initializing the client: `Error: Failed to parse target consul://my-service`. It'd appear that the client by default will use the `DnsResolver` but the regex does not support any schemes besides `dns:`.

The way I'm trying to map my target to the resolver is through the target's scheme, but perhaps there's a better way to do this? Was using changes in https://github.com/grpc/grpc-node/pull/1049 and https://github.com/grpc/grpc-node/pull/1015 as reference.

### Reproduction steps

```js
registerResolver('consul:', ConsulResolver);

const client = new grpc.Client(
  'consul://my-service,
  grpc.credentials.createInsecure()
);
```

### Environment
 - OS X
 - Node version 10.16.0
 - Node installation via nvm
 - @grpc/grpc-js@0.6.2

**Comment by murgatroid99** [comment]
That `registerResolver` API is not supposed to be part of the library's public API, so I would generally not recommend using it at all. That being said, that code looks like it should work. Maybe adding some debugging logs to `registerResolver` and/or `createResolver` will help figure out what's happening.

**Comment by danschultz** [comment]
@murgatroid99 thanks for the reply. 

> That registerResolver API is not supposed to be part of the library's public API, so I would generally not recommend using it at all.

Yep, I suspected this was the case. Is there any intention of making this part of the public API in the future? I'm looking for similar functionality of [`NameResolver`](https://grpc.github.io/grpc-java/javadoc/io/grpc/NameResolver.html)s in the Java gRPC lib (I understand that is experimental as well) to handle service resolution in clients.

> Maybe adding some debugging logs to registerResolver and/or createResolver will help figure out what's happening.

I'm hitting the same issue as reported in https://github.com/grpc/grpc-node/issues/1044. It'd appear that your fix correctly handles dashes in the target, however, adding any scheme will cause the same exception reported in #1044. For example, `my-service:1234` is handled correctly, but `http://my-service:1234` throws an exception.

Because of this, I'm unable to use `consul://my-service` to map a scheme to my Consul resolver.

**Comment by murgatroid99** [comment]
It may be possible for the `Resolver` API to eventually be made public, but it wasn't designed with that in mind and we are constrained by our own requirement to match the behavior and API of our other `grpc` Node library as much as possible. It would be very difficult to expose the same API in the other library.

The failure you are seeing is not the same as the one in #1044, in the sense that your code path should never be touching the DNS resolver at all. Based on the code at the beginning of the issue, `getDefaultAuthority` in `resolver.js` should never be calling `DnsResolver.getDefaultAuthority` at all, as your stack trace shows. That implies that there is a bug in either `registerResolver` or `getDefaultAuthority` in `resolver.js`, which is why I think it would help to add logging there.
