### ISSUE TITLE
Can't distinguish between empty array [] and undefined

### ISSUE THREAD

**Issue by Jeff-Tian** [grpc/grpc-node#1202]
### Problem description
A clear and concise description of what the problem is.
Similar to #434 , 

proto:

```
    rpc ArrayArg (ArrayArgRequest) returns (ArrayArgResponse) {

    }


message ArrayArgRequest {
    repeated string a = 1;
}

message ArrayArgResponse {
    repeated string a = 1;
}
```

Implementation

```
function arrayArg(call: any, callback: any) {
  const a = call.request.a;
  console.log('a ====== ', a);
  callback(null, { a: a });
}
```
If client invoke the ArrayArg function with empty array [] :

```
grpc.xxxService.ArrayArg({a: []})
```
By default, then inside the implementation the `call.request.a` would be undefined. 

If we add the options `arrays: true` to loadPackageDefinition, then even we invoke the method 
```
grpc.xxxService.ArrayArg({})
```
Then inside the implementation the `call.request.a` would be an empty array: [].

However, undefined and [] have different meanings, we need to distinguish them.

Let's say `a` is a field in database, we are implementing CRUD operations. Then `a = []` means delete all items of `a`, and `a = undefined` means only update other fields and leave `a` unchanged.

### Reproduction steps
See above

### Environment
 - OS name, version and architecture: macOS Mojave 10.14.2
 - Node version 10.15.1
 - Node installation method  brew
 - Package name and version gRPC@ 1.24.2

**Comment by Jeff-Tian** [comment]
I also asked this question on StackOverflow: https://stackoverflow.com/questions/59064092/how-to-distinguish-not-provided-and-empty-array-in-grpc-service

**Comment by nicolasnoble** [comment]
Your question is slightly more about protobuf than grpc-node, and would be more suited over at their repository: https://github.com/protocolbuffers/protobuf

But the gist of the problem is that the protobuf encoding doesn't distinguish between these cases. Since protobuf is language-agnostic, it doesn't understand the conceptual nuance of "undefined" versus "[]" of Javascript.

If you need to pass additional information inside the proto in order to distinguish between the two cases.
