### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by SephReed** [grpc/grpc-node#1266]
https://github.com/firebase/firebase-admin-node/issues/785#issuecomment-587938581

**Comment by murgatroid99** [comment]
Can you include the first several lines of log output from `npm install`? It should include a line about a download failing.

**Comment by nicolasnoble** [comment]
The fact this is failing with a warning-as-error issue means this is most likely an older version of the extension, against a newer version of node. Please either try to see your grpc version upgraded (which could be tricky due to transitive dependencies), or to downgrade your version of nodejs so you can catch a prebuilt binary.

**Comment by SephReed** [comment]
For now, I just have firebase disabled.  At some point I'm sure I'll want it back, and I'll see then if this works.  Sorry.
