### ISSUE TITLE
Including gRPC module to an Electron app dramatically increases the size

### ISSUE THREAD

**Issue by oguzeroglu** [grpc/grpc-node#1283]
Hello all,

Including the gRPC module to our Electron app increases its size by around 77 MBs (on a MacOS build, but similar in other platforms as well).

We use the electron-rebuild tool to integrate the gRPC into Electron.

While 77 MBs are no big deal, we're curious if there are suggested ways to minimize the size of the built app.

Best regards

**Comment by murgatroid99** [comment]
Unfortunately, that's kind of the nature of the beast. The gRPC module is complex and large, and it's worse on Electron because we need to statically link in BoringSSL.

I do want to note that we recommend against using electron-rebuild. We distribute precompiled binaries for Electron.

One alternative, if you can get the library you depend on to change, is to use the `@grpc/grpc-js` package instead of `grpc`. It has most of the same functionality as `grpc`, and it doesn't have the native module.

**Comment by xpirt** [comment]
hello @murgatroid99 there is not the precompiled binaries for electron 7.1. is it possible to get those build as well?

latest build seems to be electron-v7.0-win32-x64-unknown, but I'd need the electron-v7.1-win32-x64-unknown one. much appreciated

**Comment by oguzeroglu** [comment]
Thanks @murgatroid99!
