### ISSUE TITLE
Expected directory: node-v83-linux-x64-musl. Found: [node-v72-linux-x64-musl]

### ISSUE THREAD

**Issue by St1myL** [grpc/grpc-node#1460]
**Grpc version:** 1.24.2

When deploying my Node.js app I have a problem with the binary file for grpc package.

**Error:**

```
Error: Failed to load gRPC binary module because it was not installed for the current system
Expected directory: node-v83-linux-x64-musl
Found: [node-v72-linux-x64-musl]
This problem can often be fixed by running "npm rebuild" on the current system
Original error: Cannot find module '/app/node_modules/grpc/src/node/extension_binary/node-v83-linux-x64-musl/grpc_node.node'
```

I tried these commands in the Dockerfile:

- `npm rebuild`
- `npm install --unsafe-perm`
- `npm install --target=13.0.0 --target_platform=linux --target_arch=x64`

Dockerfile ([found here](https://github.com/alextanhongpin/node-grpc-base#docker-image)):

```
FROM node:lts-alpine
WORKDIR /app

COPY package*.json ./

RUN apk add --no-cache --virtual .gyp \
        python \
        make \
        g++ \
    && npm install \
    && apk del .gyp gcc g++ python

COPY . .

RUN npm run build

EXPOSE 9080

CMD ["npm", "start"]
```

Also I tried to configure binaries' location, but didn't found node-v83-linux-x64-musl. [Configure binaries location](https://www.npmjs.com/package/grpc#configure-binaries-location)

**Comment by murgatroid99** [comment]
Module version 83 corresponds to Node 14, not 13. Unfortunately, we have not yet published binaries for Node 14, so it's going to be difficult to get that working. You should still be fine with Node 12. If you switch to `node:12-alpine`, you can install the proper binary file either by running `npm rebuild` in the Dockerfile (may also need the `--unsafe-perm` argument), or by running `npm install --target=12.0.0 --target_platform=linux --target_arch=x64 --target_libc=musl` outside of the docker image.

**Comment by St1myL** [comment]
Thank you for your help!

**Comment by laike9m** [comment]
Hi @murgatroid99, is there a place where I can check the supported node version?

**Comment by murgatroid99** [comment]
For now, it's not exactly made to be read by humans, but our [build script](https://github.com/grpc/grpc-node/blob/grpc%401.24.x/.github/workflows/build.yml) has a list of the Node and Electron versions that we are building for.

**Comment by laike9m** [comment]
Thanks. I do think exposing this information is vital to developers and can reduce astonishment.

**Comment by murgatroid99** [comment]
Almost all the time, the answer will be that the latest versions of Node and Electron are supported, with probably a week of leeway after new versions are released. We had a period when our build was not working and we could not publish updates, but I don't think that will happen again.

**Comment by kaomimarketing** [comment]
We keeping getting an error asking for node-v88-linux-x64-glibc which seems to versions above Node.js 15.0.0. Though the latest version available from gcr.io/cloud-builders is Node js 14.10.0.

I've tried 
`npm install --target=12.0.0 --target_platform=linux --target_arch=x64 --target_libc=musl` 
within the cloudbuild.yaml to no success.

✔  functions: Finished running predeploy script.
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
✔  functions: required API cloudfunctions.googleapis.com is enabled
✔  functions: required API cloudbuild.googleapis.com is enabled
i  functions: preparing functions directory for uploading...

Error: Error parsing triggers: Failed to load gRPC binary module because it was not installed for the current system
Expected directory: node-v88-linux-x64-glibc
Found: [node-v83-linux-x64-glibc]
This problem can often be fixed by running "npm rebuild" on the current system
Original error: Cannot find module '/workspace/functions/node_modules/grpc/src/node/extension_binary/node-v88-linux-x64-glibc/grpc_node.node'

`steps:
  # Deploy firebase  
  - name: 'gcr.io/$PROJECT_ID/firebase'
    args: [ 'use', '$PROJECT_ID']

  # Packages
  - name: 'gcr.io/cloud-builders/npm:latest'
    dir: 'functions'
    args: ['install'] 

  # Build
  - name: 'gcr.io/cloud-builders/npm'
    dir: 'functions'
    args: ['rebuild', '--unsafe-perm'] 
   
    # Deploy functions
  - name: 'gcr.io/$PROJECT_ID/firebase'
    args: [ 'deploy', '--only', 'functions']`

**Comment by murgatroid99** [comment]
The extended command I suggested was specifically for installing the library on a different system than the one you are deploying it on. If you are installing the library on the same system where you are running it, you should just run `npm install`.

If you are installing and running the library on different systems, you should use that extended command, but the parameters are specific to the system where you are running the code. In particular, the `--target` argument needs to be set to the version of Node that you will be running the code on. In this case, the error says that it is looking for `node-v88-linux-x64-glibc`, and module version 88 corresponds to Node 15, so you need the argument `--target=15.0.0`.
