### ISSUE TITLE
@grpc/grpc-js: The Stream "status" event is not triggered when the "data" event is not listening

### ISSUE THREAD

**Issue by alienvspredator** [grpc/grpc-node#1509]
### Problem description
The Stream "status" event is not triggered when the "data" event is not listening.

### Reproduction steps
This piece of code reproduces the problem:
```ts
client.someStream(request).on("status", s => console.log(s)); // Does not call.
```

But this piece of code works correctly:
```ts
client.someStream(request)
    .on("data", () => {}) // Listen "data" event
    .on("status", s => console.log(s)); // Prints status
```

### Environment
 - OS name, version and architecture: Linux Ubuntu 16.04, 20.04
 - Node version: 11.1.0
 - Package name and version @grpc/grpc-js@0.8.1-1.1.2

**Comment by murgatroid99** [comment]
This is working as intended. You have to drain the incoming messages for the call to end. You are not necessarily required to do so using a `data` event listener. You could also explicitly call the `read` method until there is nothing else to read to achieve the same thing.

This is the result of the combination of two different design choices:

 - The local reader needs to be able to exert backpressure on the remote writer so that the local buffer of incoming messages do not grow arbitrarily large. If the local reader is not reading, the library stops accepting messages from the remote end. This means that in general, the library cannot process all incoming messages unless the user is actively reading.

 - An invalid incoming message causes a request that would otherwise succeed to fail with a specific non-OK status. This means that the library cannot finalize the status until it has processed all incoming messages.

Put these together, and you can see that the status cannot be fully determined unless you are reading from the call.

**Comment by alienvspredator** [comment]
Thank. I would like to add some details. The gRPC `ClientReadableStream` is a subset of the NodeJS [`stream.Readable`](https://nodejs.org/api/stream.html#stream_class_stream_readable). This behavior is described in the [NodeJS documentation](https://nodejs.org/api/stream.html#stream_event_end). I should to use [`stream.resume()`](https://nodejs.org/api/stream.html#stream_readable_resume) in my case.

**Comment by murgatroid99** [comment]
Yes. `stream.resume()` will have essentially the same effect as `stream.on('data', () => {})`.
