### ISSUE TITLE
Add support for "grpc.service_config_disable_resolution" option in grpc-js

### ISSUE THREAD

**Issue by matetukacs** [grpc/grpc-node#1518]
Any news on when grpc-js will support the option to disable service config resolution? We are observing dns lookups take much longer than expected (up to 500ms) when the grpc library makes a simultaneous TXT DNS query (the TXT queries always fail). Based on issues I found in repos of other grpc implementations the general advice is to turn off service config resolution in order to make the library stop making TXT queries. We are observing the same thing happening both in case of node-firestore and node-pubsub. 

node-firestore version: 3.5.5
node-pubsub version: 2.0.0

We also tried using the c++ based node grpc library, however, firestore does not seem to be compatible with it.

Thanks in advance!

**Comment by murgatroid99** [comment]
What version of `@grpc/grpc-js` are you using? I made a change that went out in version 0.7.4 back in March that should have fixed this delay by allowing name resolution to finish without waiting for the TXT query response. 500ms is actually a lot smaller than the previously reported delays, though, so maybe there's something else going on here.

Can you share the observations that led you to conclude that the delay is caused by the TXT queries, so that I can get a better idea of what's happening here?

**Comment by matetukacs** [comment]
Sorry for the late response on this. Our observations were incorrect! We were able to get rid of the failing TXT queries and I can confirm this had no effect on the DNS resolution time. 

We have since also fixed the issue with long-lasting DNS queries, the issue was on our side.

Thanks!

**Comment by kleinsch** [comment]
Would love this feature. While we're not seeing functional or performance issues in our client calls, our DataDog traces periodically show errors bc of these failing TXT record queries. Would be great to not have to carve out exceptions in our alerting or spend time creating TXT records for service config we're not using.

**Comment by murgatroid99** [comment]
This option is now supported in version >=1.8.1
