### ISSUE TITLE
grpc-js not support all grpc options

### ISSUE THREAD

**Issue by zyf0330** [grpc/grpc-node#1593]
### Is your feature request related to a problem? Please describe.
https://github.com/microsoft/etcd3/issues/136

### Describe the solution you'd like
I use grpc-js v1.1.7
I want to set all options, but some of them seems to not be supported. So keepalive doesn't work.
```

  // reconnect
      'grpc.initial_reconnect_backoff_ms': 500,
      'grpc.min_reconnect_backoff_ms': 500,
      'grpc.max_reconnect_backoff_ms': 2000,
      // keepalive
      'grpc.http2.max_pings_without_data': 0,
      'grpc.http2.min_time_between_pings_ms': 10000, // default value of etcd server is 5s
      'grpc.keepalive_time_ms': 10000,
      'grpc.keepalive_timeout_ms': 5000,
      'grpc.keepalive_permit_without_calls': 1,
```
### Describe alternatives you've considered
nothing

**Comment by murgatroid99** [comment]
That is correct. The set of options currently implemented is listed at the end of [this document](https://github.com/grpc/grpc-node/blob/master/PACKAGE-COMPARISON.md). 

First, since you talked about a problem with keepalives, I want to mention that there is currently a pending bugfix for a bug that was causing the client to send too many pings. That was going to be part of a larger release but I can publish it sooner now that I know it might have this kind of impact. In what way are keepalives not working for you?

I would also like to note that among the ones you listed that are not yet implemented, `grpc.min_reconnect_backoff_ms` probably wouldn't do anything if it is less than or equal to `grpc.initial_reconnect_backoff_ms`. The same is true of `grpc.http2.min_time_between_pings_ms` and `grpc.keepalive_time_ms`. Also, `grpc.http2.max_pings_without_data: 0` is the default behavior of `@grpc/grpc-js` due to some limitation in how keepalives are implemented in this library. The odd one out is `grpc.keepalive_permit_without_calls`

**Comment by zyf0330** [comment]
I use etcd3 to connect to etcd server. I test keepalive feature with above grpc options by disabling network interface, and found when etcd3 uses grpc-js, connection cannot be detected to be broken, but when use grpc-node, it can be.

**Comment by zyf0330** [comment]
I have test with tiny codes. This problem is related to @grpc/grpc-js in client, no matter server uses @grpc/grpc-js or grpc-node library.

**Comment by murgatroid99** [comment]
Support for `grpc.keepalive_permit_without_calls` is now out in version 1.2.0. I expect that this will solve your problem.
