### ISSUE TITLE
[protobufjs] Error Cannot read property 'emptyArray' of undefined with rollup

### ISSUE THREAD

**Issue by vicb** [grpc/grpc-node#1623]
This project has a dependency on [protobufjs](https://github.com/protobufjs/protobuf.js) in [proto-loader](https://github.com/grpc/grpc-node/blob/03aaeb78a25fa847642a1cdd217635b64524c2ab/packages/proto-loader/package.json#L43)

[protobufjs](https://github.com/protobufjs/protobuf.js) has a known issue with rollup: https://github.com/rollup/rollup/issues/2747

Which means that projects using rollups might have build errors when using grpc-node.

I am creating this issue for 2 purposes:
- To make it easier to debug the `Cannot read property 'emptyArray' of undefined with rollup` when it is generated,
- To suggest to switch to other proto alternatives. I have been using [protobuf-ts](https://github.com/timostamm/protobuf-ts) that generates type safe typescript code and look more robust that protobufjs.

Ref: https://github.com/protobufjs/protobuf.js/issues/1503

**Comment by murgatroid99** [comment]
My view here is that if a piece of code works in Node when used directly, but breaks when a tool like Rollup is used, that is a fault in Rollup or the Rollup plugin mentioned in the linked issue.

The protobuf-ts library in particular appears to be very different from Protobuf.js, and in particular it uses code generated by `protoc` instead of a runtime `.proto` parser. Using it would require a complete overhaul of the proto-loader library and I don't think that is worth doing just to work around a bug in a third-party tool.

**Comment by vicb** [comment]
@murgatroid99 what you said makes sense - especially in an ideal world.

I have worked around the issue by not bundling the `@google-cloud` lib when using rollup, i.e.

```js
export default [
  {
    input: 'src/index.ts',

    // ...

    external: [/@google-cloud/],
  },
```

Maybe this issue should be closed now ? 
Hopefully it could still help some people.

**Comment by vicb** [comment]
FYI I asked Timo the maintainer of protobuf-ts how complex it would be to support creating protocol buffer encoders and decoders at rutime and it seems to be doable, see https://github.com/timostamm/protobuf-ts/issues/32

**Comment by murgatroid99** [comment]
That issue seems to have settled on parsing the Protobuf.js JSON descriptor format, which is not really the main use case of this library. Loading `.proto` files is an important feature.

Personally I think the most useful path forward here is to get the Rollup issue fixed. I don't think it's worthwhile to play whack-a-mole working around issues in random tools that violate otherwise valid assumptions about what code will and will not work on Node.
