### ISSUE TITLE
ServerWritableStream destroyed before closed

### ISSUE THREAD

**Issue by thosil** [grpc/grpc-node#1644]
### Problem description
Writing server side code, I'm implementing an rpc that send a stream of messages.
If at a point I write something invalid, the ServerWritableStream (call) is destroyed and not writable anymore, but nothing has been sent to the client which is still waiting endlessly for the next message.
If the client disconnect, the server receive the cancelled signal as expected and finally close the connection.

As the call has been destroyed, I can't find a way to let know the client that the stream is over.

### Reproduction steps
```typescript
import { ServerWritableStream } from 'grpc';
import { ImyServer } from './protos/MyServer_grpc_pb';
...

export class GRPCServer implements ImyServer {
  ...
  getData(call: ServerWritableStream<DataRequest, DataResponse>): void {
    const res = new DataResponse();
    res.setSomeNumber(NaN); // Typescript is ok with that, and this method does not raise an Error
    call.write(res); // but it will raise an error here

    call.on("error", (err) => {
      // here call.writable == false
      call.end(() => {
        // will never go here
      });
    });
  }
}
```

### Environment
 - OS: Linux Ubuntu 20.04 amd64
 - Node version: v14.14.0
 - Node installation method: nvm
 - If applicable, compiler version N/A
 - Package name and version: gRPC@1.24.4

### Additional context
on the client side, I'm listening on these events: "data", "end", "error", "close", none of them is called.

**Comment by murgatroid99** [comment]
I'm surprised that you're seeing that behavior, because we have tests for that exact scenario [here](https://github.com/grpc/grpc-node/blob/grpc%401.24.x/packages/grpc-native-core/test/surface_test.js#L726-L830) (the serialization function on the server throws an error, and the client should see an INTERNAL error as a result).

I suggest switching from `grpc` to `@grpc/grpc-js`. It might help, or at least be easier to debug, and either way, `grpc` is going to be deprecated and `@grpc/grpc-js` will be the primarily maintained implementation going forward.

**Comment by thosil** [comment]
Thanks @murgatroid99.
I switched to grpc-js. I keep you posted if I have a different behavior.

**Comment by thosil** [comment]
I confirmed that it's ok with grpc-js
Thanks!
