### ISSUE TITLE
Why Linux node-grpc rebuild size so big?

### ISSUE THREAD

**Issue by jazzwsr** [grpc/grpc-node#1676]
Electron version: V7.3.3
grpc version: V1.0.0

result: when i use electron-builder build a Linux unpackaged file , the app.asar include grpc so large, compare with build from windows, as is shown in:
![image](https://user-images.githubusercontent.com/8381304/105938035-bb125f80-6091-11eb-8e05-e00ede8a2aee.png)

**Comment by murgatroid99** [comment]
First of all, the `grpc` library will be deprecated soon, so I suggest using its replacement `@grpc/grpc-js` instead. That library does not have large binary files like you see here.

Regarding your specific question, I am unsure why the Linux files would be larger. If anything, I would expect them to be larger on Windows because that build statically links additional libraries. I do not recognize that `bin` directory; it may be part of the output of `electron-builder`. In general we do not recommend using tools like `electron-builder` because we distribute precompiled binaries for Electron. Please see [the grpc library README](https://www.npmjs.com/package/grpc#about-electron) for detailed information about installing the library for use with Electron.

**Comment by jazzwsr** [comment]
> First of all, the `grpc` library will be deprecated soon, so I suggest using its replacement `@grpc/grpc-js` instead. That library does not have large binary files like you see here.
> 
> Regarding your specific question, I am unsure why the Linux files would be larger. If anything, I would expect them to be larger on Windows because that build statically links additional libraries. I do not recognize that `bin` directory; it may be part of the output of `electron-builder`. In general we do not recommend using tools like `electron-builder` because we distribute precompiled binaries for Electron. Please see [the grpc library README](https://www.npmjs.com/package/grpc#about-electron) for detailed information about installing the library for use with Electron.

That's so cool, now i got app.asar/node_modules/@grpc is 870.8KB and valid, my app lost weight. tks~

**Comment by jazzwsr** [comment]
> What's inside them?
> and What's the output of `ls -lh` ?

 large binary files, replace by @grpc/grpc-js.
