### ISSUE TITLE
grpc-js fails to invoke client stream 'status' listener when 'data' event not subscribed to

### ISSUE THREAD

**Issue by michaelgoin** [grpc/grpc-node#1696]
### Problem description

When a grpc-js client stream is subscribed to the 'status' event but not subscribed to the 'data' event, when the server has written data to the stream and then sends a status (0 OK for example), the client stream 'status' event will not be invoked.

This problem does not seem to occur if the server never writes data to the stream or if the 'data' event is subscribed to. 

This bit us because we relied on the status to know to reconnect to a new stream and ended up getting `ERR_STREAM_WRITE_AFTER_END` errors.

### Reproduction steps

Here's a reproduction I've put together. Our production code is a bit different but this seems to be the simplest way I can represent the problem.

https://github.com/michaelgoin/grpc-js-status-repro

Particularly, see the failing test case here: https://github.com/michaelgoin/grpc-js-status-repro/blob/main/test.js#L7-L49

### Environment
 - OS name, version and architecture: Variety of Linux and MacOS environments
 - Node version: 10-14
 - Node installation method: nvm locally, unsure of situation for our clients
 - Package name and version: grpc-js@1.2.5+, spot checked 1.1.0 and 1.2.0 and also failing.

**Comment by murgatroid99** [comment]
The application needs to drain incoming messages before status can be output. This preserves the ordering of messages and the status. Since readable streams can be paused and resumed, the library cannot distinguish between a user that is not interested in reading any messages and a user that has temporarily paused reading messages, which means that it cannot skip over messages in a paused stream to deliver a status.

**Comment by michaelgoin** [comment]
Ah interesting. I'm not sure I've encountered a situation before where I needed to subscribe to one event to be able to receive another and not sure how I'd know I'd need to do that without messing it up. Your explanation seems reasonable but ultimately the usage feels unintuitive. Perhaps I just don't have enough experience around streams handling.

That being said, I'd guess the by far most common case is if something is written from the server... clients need/want to do something with it. In our case, the server is just sending details that we don't use directly but log at certain levels. We weren't subscribing at the levels we weren't using the data for anything.

**Comment by murgatroid99** [comment]
The built in `end` event in the `Readable` stream class has exactly the same behavior as what I described, as documented [here](https://nodejs.org/api/stream.html#stream_event_end). The stream you get from the grpc library is actually a subclass of that class, so that behavior should be unsurprising to anyone familiar with Node streams. To be fair, that behavior could be documented better for the `status` event.

**Comment by michaelgoin** [comment]
I was wondering if was a node stream thing given how things seem to be implemented (and debugging I'd tried). Good to know, guess I just haven't encountered thus far.

Thanks! I'll close this out.
