### ISSUE TITLE
Implement a "fromObject" for proto-loader

### ISSUE THREAD

**Issue by LeeStephen** [grpc/grpc-node#1730]
### Is your feature request related to a problem? Please describe.
I have a Google PubSub topic that has been schema'd to respect a proto file. The messages entering the topic are encoded in JSON. I want to reuse existing service code that has been written to handle requests coming in via gRPC. The service logic has been typed using the Typescript generator supplied in v0.6.0-pre17.

Since the service code's argument expects to have properties set to default values, but the PubSub topic does not set default values when a client does not supply them in the initial message, there is a type mismatch between those two objects.

### Describe the solution you'd like
The new Typescript generator exposes two interfaces per message type on the proto file. One is the more "forgiving" object that clients would supply, and the other is the "stricter" object that represents the result of the former after getting processed via proto-loader. I would like some feature that would allow me to translate objects that respect the former interface into the latter (some kind of "fromObject"). This would allow me to reuse the same service code and proto file to expose a non gRPC (in this case, async via PubSub) endpoint for my service.

### Describe alternatives you've considered
Without this feature, I am currently doing the translations manually. The JSON message I receive from PubSub is being translated into an object that maps the output coming out of proto-loader.

**Comment by ludusrusso** [comment]
This feature would be great also for me!

**Comment by murgatroid99** [comment]
I think this change would be out of scope for this library. The types generated by that TypeScript generator just describe the types of objects handled by this library. If you are using objects with those types outside of the context of gRPC and the protobuf serialization that this library does, that use case is not really relevant to this library.

**Comment by LeeStephen** [comment]
Protobuf.js has the concept of a "valid message", and seems to describe translating plain javascript objects into valid messages (according to the protobuf). They define a "fromObject" that can translate a plain javascript object into a "valid message" object relative to a protobuf message type. Right now, this is how I am translating the object, but it requires I introduce protobufjs as a dependency to my project.

Would it be more appropriate for this to be done in grpc-js? After loading a package definition, the message types could have an additional "fromObject" method exposed to load these plain javascript objects and return valid messages.

If none of this fits under the "grpcjs/proto-loader" family of tools, are there any alternative solutions I can employ which would allow me to reuse my service code?

**Comment by murgatroid99** [comment]
> After loading a package definition, the message types could have an additional "fromObject" method exposed to load these plain javascript objects and return valid messages.

Loading a package definition does not provide the message types as concrete objects. There's nothing to put a `fromObject` method on. This is what I mean when I say that the generated types are just descriptive.

The generated types are really just representations of the protobuf semantics of serializing and deserializing objects, specifically how protobufjs handles those operations. If you want those semantics in a context where you're not using gRPC, using protobufjs yourself is probably the best approach. `fromObject` followed by `toObject` with the right options would get the object you are looking for.

Alternatively, it is possible to do this using the current proto-loader library, but it is inefficient. You can use the `serialize` and `deserialize` functions included in the relevant method definition. This is inefficient because it serializes the data to binary and then has to parse that same binary, but you should end up with an object of the type you want.
