### ISSUE TITLE
How to set proper 'content-length' in metadata when sending client request?

### ISSUE THREAD

**Issue by HappyZombies** [grpc/grpc-node#1746]
I am trying to set content-length via the metadata but to get the actual length of bytes being sent seems to be...tricky or maybe I just don't understand how to do it? 

### Reproduction steps

I have a project which you guys can clone and run

https://github.com/HappyZombies/grpc-content-length

Note that the client has different ways to get the "length" of the content being sent. I noticed that the only that works is when I call the `.requestSerialize` method and add extra 5 bytes to it. But I only found that out cuz of this [stackoverflow issue](https://stackoverflow.com/a/60461010/5339639) which then links to [this document](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md) (which btw doesn't mention 5 extra bytes being added...unless I'm totally missing it)

Also an interesting note, when the server uses the "grpc" module (NOT @grpc/grpc-js), all of the examples of content-length being set from the client seem to go through without an error. 

### Environment
- Mac OS X, 10.15.7
- Node version - v12.11.1
- Package name and version

### Additional context

If you need more examples or understanding of what I am trying to do let me know. Thanks

**Comment by murgatroid99** [comment]
What is your objective here? Why do you need the `content-length` header? The gRPC libraries do not send it because it general, the content length is not known at the time that headers are being sent, particularly when doing streaming.

In the protocol document you linked, the section about how messages are encoded says this:

> The repeated sequence of Length-Prefixed-Message items is delivered in DATA frames
>
> - Length-Prefixed-Message → Compressed-Flag Message-Length Message
> - Compressed-Flag → 0 / 1 # encoded as 1 byte unsigned integer
> - Message-Length → {length of Message} # encoded as 4 byte unsigned integer (big endian)
> - Message → *{binary octet}

The compressed flag and message length add up to the 5 bytes you are seeing.

In your code, there is no reason that `JSON.stringify(toSend)` would give you any relevant information. That is simply a completely different encoding than the protobuf encoding your code is actually using.

Regarding the difference between the `grpc` and `@grpc/grpc-js` modules, they use completely separate HTTP/2 implementations, so there is no surprise that they would have some differences in behavior. In particular, the HTTP/2 implementation in `grpc` was created specifically for use with gRPC, and since the `gRPC` protocol does not use the `content-length` header, it probably just ignores it.

Note that if/when compression support is added, the compressed message will have a different length, which you won't know ahead of time.

**Comment by HappyZombies** [comment]
@murgatroid99 thank you so much for the very thorough explanation to my questions. I think I completely understand now what I was doing wrong. It seems like I was using `content-length` incorrectly and didn't have an understanding of the protobuf encoding. Again, your excellent explanation really made it all clear for me! Thanks a lot 👍
