### ISSUE TITLE
Deadline documentation

### ISSUE THREAD

**Issue by hardboiled** [grpc/grpc-node#1872]
### Deadline Documentation
I was trying to figure out if this library supported [deadlines](https://grpc.io/blog/deadlines/), and found [this issue](https://github.com/grpc/grpc-node/issues/541). Initially, I was passing `deadline: number` as ChannelOptions similarly to. how the issue link did so, but that didn't work.

Upon looking at the [code](https://github.com/grpc/grpc-node/blob/9d1e3342fda0845ee9b80db824689fff5860cfce/packages/grpc-js/src/server-call.ts#L50), the actual way to do this is to just add a `grpc-timeout` to the metadata like so:

```ts
metadata.set('grpc-timeout', `${GRPC_DEADLINE_IN_MILLISECONDS}m`)
```

I tested it, and it worked. However, I wanted to double-check: is this going to be supported in later versions of the library? I'm asking because the interface (i.e. setting metadata directly) is a bit different than the other supported languages, and because the `GRPC_TIMEOUT_HEADER` is not exported.

### Describe the solution you'd like
I want to make sure that when I update this package in the future, this code will continue to work. If this is how to implement deadlines going forward then great! Otherwise, I would appreciate any advice you could give to future proof my deadline code to ensure it continues to work across upgrades. Thanks!

**Comment by murgatroid99** [comment]
That linked issue is not passing the deadline as a channel option, but as a call option (i.e. per request). A deadline is an absolute point in time that determines when the call should end with the corresponding error, so it needs to be set separately for each call. You can use a `Date` to represent it rather than a number, which may be helpful.

You should not pass that header directly. It bypasses client-side deadline checking, and will never trigger if the deadline is exceeded because the server never responds at all.

**Comment by hardboiled** [comment]
Based on your recs, I was able to find the right type definitions for `grpc.CallOptions` for building the call correctly. I tested it with interceptors that intentionally delay the send message, and the deadlines triggered as you said.

Thanks for your help!
