### ISSUE TITLE
Why grpc-node didn't use bazel as default build tool?

### ISSUE THREAD

**Issue by Hanggi** [grpc/grpc-node#1884]
I found that both grpc and grpc-java are using bazel as build tool.

Are there any benefits to using bazel build grpc-node?

Thank you.

**Comment by murgatroid99** [comment]
This is a solution looking for a problem. You use a tool because it solves a problem. If you don't have a problem that that tool will solve, there's no reason to use the tool.

Why are some of the other libraries using bazel? Because it solves problems for them. Why aren't the libraries in this repository using it? Because it wouldn't solve any problems for them.
