### ISSUE TITLE
proto-loader TS generator gives invalid ServiceDefinition types

### ISSUE THREAD

**Issue by MasterOdin** [grpc/grpc-node#1886]
### Problem description

When using the typescript generator in the `@grpc/proto-loader` library, the generated `ServiceDefintion extends grpc.ServiceDefinition` does not compile correctly.

The error from tsc is:

> Generic type 'MethodDefinition<RequestType, ResponseType>' requires 2 type argument(s).

Looking at the source code, it looks like `@grpc/grpc-js` is expecting singular `RequestType` and `ResponseType` args:

https://github.com/grpc/grpc-node/blob/9d1e3342fda0845ee9b80db824689fff5860cfce/packages/grpc-js/src/make-client.ts#L49-L51

whereas `@grpc/prot-loader` is generating it with four:

https://github.com/grpc/grpc-node/blob/9d1e3342fda0845ee9b80db824689fff5860cfce/packages/proto-loader/bin/proto-loader-gen-types.ts#L551

### Reproduction steps

https://github.com/badsyntax/grpc-js-typescript/tree/master/examples/grpc-proto-loader has this error, see:

https://github.com/badsyntax/grpc-js-typescript/blob/2bc7e2f93e3412e24ed3fdad9c09e6e566f6caf7/examples/grpc-proto-loader/proto/example_package/Example.ts#L50-L55

### Environment
 - OS name, version and architecture: macOS
 - Node version [e.g. 8.10.0]: 12.20.0
 - Node installation method [e.g. nvm]: brew
 - Package name and version: `@grpc/proto-loader@0.6.4`

**Comment by murgatroid99** [comment]
That is very surprising, because I have code generated by that version of proto-loader that is working in tests. The generated code should work, because it doesn't actually use the `MethodDefinition` type you linked to; it uses this one in the proto-loader library itself, which does have 4 type arguments:

https://github.com/grpc/grpc-node/blob/master/packages/proto-loader/src/index.ts#L118-L129

Can you verify that you are compiling against the same version of the proto-loader library that you are using to generate your code?

**Comment by MasterOdin** [comment]
How embarrassing. It looks like it was some weirdness with yarn + packages. Wiping the `node_modules` folders out and re-installing and now it works as expected.

Sorry about that!
