### ISSUE TITLE
Error in `node`: corrupted double-linked list: 0x....

### ISSUE THREAD

**Issue by rivertam** [grpc/grpc-node#197]
Hi there

So I'm using grpc on a Jetson TX-2 (ARMv8 architecture) with node 8.9.4 (also tried with 9.6.1). When I simply `require('grpc')`, everything works fine. However, when I'm in my project (can't share the project, but I don't think it should really matter much), I get

```
Error in `node`: corrupted double-linked list: 0x...
```

where `0x....` is a pointer.

I thought it would be occurring inside a native module, but it seems to actually be happening when grpc requires `src/common.js` in `src/client.js` (`var client = require('./common');`). If I put a `console.log` before that line, it prints. However, if I put a `console.log` inside `src/common.js` at the very top (before or after `'use strict';`), that does not print.

It seems like it might be a node issue, but I haven't run into this issue with any other libraries. When I run it on x86, I encounter no issues, and this issue actually only occurs sometimes (again, only within the context of my project). I thought I'd post here to see if anyone knew what's up.

The version of `grpc` I'm using is 1.9.1.

**Comment by murgatroid99** [comment]
If this is happening in your project when you call `require('grpc')`, can you share what code you run before that line runs? Do you have any unusual Node configuration settings?

**Comment by rivertam** [comment]
@murgatroid99 Thank you so much for your very timely response.

I'm requiring a few files to get to the `require('grpc')` call. Essentially it goes:

```javascript
// entry file
require('@namespace/my-other-module');

// @namespace/my-other-module/index.js
require('./src/server.js');

// @namespace/my-other-module/src/server.js
const { /* ... */ } = require('lodash/fp');
const grpc = require('grpc');
```

I don't believe any other lines of code are running before that. Any ideas?

**Comment by rivertam** [comment]
Shockingly, I tried moving the `lodash/fp` require below the grpc require, and it made it more stable (crashes less often, possibly a lot less), but it still does crash on the same line.

**Comment by murgatroid99** [comment]
So, to be clear, if you have a script that just does `require('grpc')` it works fine, but if you have a script that requires another script that requires grpc, it crashes?

**Comment by rivertam** [comment]
@murgatroid99 Pretty much. :/ That's what I've managed to understand from the couple hours I've been playing with permutations.

**Comment by rivertam** [comment]
I understand this is a particularly tricky issue to talk about, especially because I don't even know if it has to do with grpc, really. However, it's pretty mission critical, so I decided to make a reproduction repo in the hopes that it might clarify. This repository does exhibit the problem I've expressed when used on a TX2 with node v9.6.1. (To reproduce, you need to run `npm install` inside the `grpc-wrapper` faux node module)

https://github.com/rivertam/require-issue-repro

**Comment by murgatroid99** [comment]
With your reproduction case, have you tried having just one module, with file `a` imports file `b`, which imports `grpc`?

Unfortunately, I probably won't have an answer soon because I don't have a TX2 to test this on. Do you know if there is a simulator for that system, and if so, whether this error reproduces on it?

I would not yet recommend using the pure JavaScript client. It is still in development, and it does not currently have the APIs for generating clients from `.proto` files or otherwise.

**Comment by rivertam** [comment]
It does fail with that example, so going through node_modules twice does not seem to be necessary. Trying again with just one require works fine (no crashes), so I'm very confused.

Do you have any kind of ARM device? The chipset is ARMv8. I think it comes down to architecture more so than the actual device itself.

**Comment by nicolasnoble** [comment]
We've been testing gRPC node sporadically on a raspberry pi. We could give it a try on it and see what happens... The model 3 is an armv8 as far as I know.

**Comment by rivertam** [comment]
Hmm, okay. We've decided to switch to WebSockets for various reasons including this, so I probably won't continue to investigate. Hopefully the issue isn't actually with node or something else. I have no problems with y'all closing the issue if there's no indication that anyone else is having the issue.

**Comment by nicolasnoble** [comment]
Well, getting to the bottom of this would be nice, still. Something that happens on exotic hardware only means that there is something wrong with the code, that is being exhibited by said exotic hardware.

Can you at provide some details about the TX2's operating system ? Raspbian is notorious for being 32 bits only for example. If your issue only happens on 64 bits arm, that'd be interesting. Also, are you running a 32 bits version of node in a 64 bits Arm OS ? Are you using the pre-compiled binary that we offer (which is 32 bits) ? Since you've censored your bug report, we can't really tell if your pointers are 32 bits or 64 bits, for instance. Etc.

**Comment by nicolasnoble** [comment]
Welp, I just tried on a raspberry pi 3 using the pi64 distribution to go in 64 bits mode and make sure that the armv8 architecture is enabled, but your repro case is working properly. Unless I get more details about your environment, I'll be stuck trying to repro that one.

**Comment by rivertam** [comment]
Node:

```javascript
> process.platform
'linux'
> process.arch
'arm64'
```

`uname -m` gives `aarch64`.

I'm not sure if we're using the pre-compiled binary. `npm i` takes a little over 2 minutes to get grpc, so I think we're compiling it each time. The pointers are 16 bytes long, btw.

I have no problem continuing to give you debugging information by the way if it helps you investigate. Just let me know if you need anything else.

**Comment by rivertam** [comment]
Also, it doesn't happen consistently. What I do to reproduce the issue is `while true; do node index.js; done` and it errors out about half the time.

**Comment by nicolasnoble** [comment]
We are definitely not publishing arm64 binaries for grpc-node, so you are bound to compile it every time. I would be now curious if I could give you the package built from a raspberry pi 64 bits and see if it loads cleanly for you - and possibly even works. I'll do that in a few hours.

I am also going to try pounding on it today for a while and see if it eventually reproduces since you say it's not happening 100% of the time.

**Comment by rivertam** [comment]
Sounds good. Please include instructions on how to actually put the binary in the right place when you do. Don't want a mistake and throw us off. =)

**Comment by nicolasnoble** [comment]
I have built and uploaded arm64 binaries for grpc 1.9.1. If you try removing and reinstalling the grpc module, it should be faster this time and not compile it, using the pre-built version instead.

I haven't been able to reproduce the problem you are experiencing, even when running it on a loop. 

Using the pre-built package will tell us if it's an issue with your build environment, or with your CPU.

**Comment by rivertam** [comment]
Definitely less frequent, but I am still incurring the same error.

**Comment by nicolasnoble** [comment]
Alright, at that point, this is going to be a one last shot in the dark. I've uploaded a new set of binaries to try and see if we can fix this one without having an actual rootcause. These binaries still work properly on my arm8 raspberry pi machine. Could you once again delete your node_modules folder and retry installing grpc and tell me if it reproduces ?

If it still doesn't fix it, I'll have to see if we can expense a TX2 module to reproduce and debug it. The main issue I see here is that this does seem like a very generic memory corruption problem, and I don't see why it should happen on the TX2 machine only, especially if you don't have any other problems on the machine whatsoever. So that would mean there is a bug somewhere in our code, very rare and elusive in nature, but exposed somehow by the TX2 CPU.

**Comment by rivertam** [comment]
@nicolasnoble Just tried and still seeing the issue. :/ I haven't seen any other issues on this machine, I don't think.

**Comment by nicolasnoble** [comment]
Alright, thanks. There is something really fishy going on there, and I don't like the idea of leaving a memory corruption bug lingering around. Getting our hands on such machine would help debugging the problem. I'll talk with management here to see if they are okay with us getting a TX2 to repro and debug that.

**Comment by nicolasnoble** [comment]
So we managed to get our hands on a TX-2 board to try and reproduce the issue, but this isn't showing up there either.

The OS on the board is an Ubuntu 16.04.4 LTS, and seems to be the same architecture as yours, so at that point, I don't really know what's going on.

```
$ cat /etc/issue
Ubuntu 16.04.4 LTS \n \l

$ lscpu
Architecture:          aarch64
Byte Order:            Little Endian
CPU(s):                6
On-line CPU(s) list:   0-5
Thread(s) per core:    1
Core(s) per socket:    3
Socket(s):             2
Model name:            ARMv8 Processor rev 3 (v8l)
CPU max MHz:           2035.2000
CPU min MHz:           345.6000
Hypervisor vendor:     (null)
Virtualization type:   full
L1d cache:             32K
L1i cache:             48K
L2 cache:              2048K
```

**Comment by rivertam** [comment]
Yeah, it looks almost identical. The corresponding `lscpu` from our board is

```
Architecture:          aarch64
Byte Order:            Little Endian
CPU(s):                6
On-line CPU(s) list:   0,3-5
Off-line CPU(s) list:  1,2
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             1
Model name:            ARMv8 Processor rev 3 (v8l)
CPU max MHz:           2035.2000
CPU min MHz:           345.6000
L1d cache:             32K
L1i cache:             48K
L2 cache:              2048K
```

**Comment by murgatroid99** [comment]
At this point, the `grpc` module has been deprecated for a couple of years, with `@grpc/grpc-js` as the recommended replacement. We have no plans to update the `grpc` module to fix this problem.
