### ISSUE TITLE
End event emitted before cancelled event on server request stream.

### ISSUE THREAD

**Issue by zachrip** [grpc/grpc-node#205]
I'm attempting to create a streaming upload service with grpc. I'm trying to handle the case where a request (upload) is cancelled but the end event seems to be called before cancelled which doesn't seem right.

I've put together an example, the output on server side is:
```
~/Projects/Playground/grpc-testing  node server.js
server: got data { upload_descriptor: '1', content: <Buffer 00> }
server: request ended false false false
server: request cancelled true true false
```

client.js:
```
const grpc = require('grpc');
const PROTO_PATH = __dirname + '/depot.proto';
const protoDescriptor = grpc.load(PROTO_PATH);
const depot = protoDescriptor.depot;

const client = new depot.Depot('localhost:50051', grpc.credentials.createInsecure());

const call = client.upload((err, data) => {
  if (err) {
    console.log(err);
    return;
  }
  console.log('got data', data);
});

call.write({ upload_descriptor: 1, content: new Uint8Array([0]) });

setTimeout(() => {
  call.cancel(new Error('there was an error'));
}, 3000);
```

server.js:
```
const grpc = require('grpc');
const PROTO_PATH = __dirname + '/depot.proto';
const protoDescriptor = grpc.load(PROTO_PATH);
const depot = protoDescriptor.depot;

const server = new grpc.Server();

server.addService(depot.Depot.service, {
  upload: (request) => {
    request.on('data', (data) => {
      console.log('server: got data', data);
    });

    request.on('error', (err) => {
      console.log('server: got error', err);
    });

    request.on('cancelled', () => {
      console.log('server: request cancelled', request.cancelled, request.finished, request.reading);
    });

    request.on('end', () => {
      console.log('server: request ended', request.cancelled, request.finished, request.reading);
    });
  },
});

server.bind('0.0.0.0:50051', grpc.ServerCredentials.createInsecure());
server.start();
```

depot.proto:
```
syntax = "proto3";

package depot;

service Depot {
    rpc upload(stream Chunk) returns (UploadStatus);
}

message Chunk {
    uint64 upload_descriptor = 1;
    bytes content = 2;
}

enum UploadStatusCode {
    Unknown = 0;
    Ok = 1;
    Failed = 2;
}

message UploadStatus {
    string message = 1;
    UploadStatusCode code = 2;
}
```

**Comment by zachrip** [comment]
A temporary fix I can use is:
```
request.on('end', () => {
  console.log('server: request ended', request.cancelled, request.finished, request.reading);

  setImmediate(() => {
    console.log('request cancelled', request.cancelled); // true
  });
});
```

**Comment by murgatroid99** [comment]
First, I would recommend not using `request.finished` and `request.reading` for anything. They are not part of the API, and do not have publicly documented meanings.

Second, I think I see what's happening here: the end of messages from the client and the cancellation from the client are two separate events that are getting reported separately by the lower level protocol implementation. When the client cancels the call, both of those events are triggered at about the same time on the server, and they can be surfaced in any order. I can see that this may decrease the usefulness of the cancellation functionality to some degree, but I wouldn't worry about it much. Cancellation is best-effort anyway, and it can easily arrive after a regular end-of-messages event, and even after you send the response from the server. If you were going to immediately send a response from the server anyway, handling the cancellation event properly probably won't make a significant difference.

As a side note, the `cancel` function doesn't take a parameter, so that error isn't actually doing anything.

**Comment by nicolasnoble** [comment]
Closing, since it got no response for a long time now.
