### ISSUE TITLE
Error: grpc-js doesn't work with FlatBuffer message (message.copy is not a function)

### ISSUE THREAD

**Issue by manhnt9** [grpc/grpc-node#2070]
### Problem description
gprc (native node module) works with FlatBuffers message but pure js version seems to be buggy with it.

### Reproduction steps
1. Write a .fbs schema file with RPC service, generate JS, TS definitions
2. In JS code, create a message using FlatBuffers builder, example:

```javascript
    const server = new PAuthClient(ServerURL, ServerCertificate)
    const builder = new flatbuffers.Builder() // create message
    
    const email = builder.createString(this.email) // add fields to message
    const password = builder.createString(this.password)  // add fields to message
    
    const service = builder.createString('___')
    const root = PAuthRequest.createPAuthRequest(builder, email, password, service)
    builder.finish(root)
    
    const buffer = PAuthRequest.getRootAsPAuthRequest(new flatbuffers.ByteBuffer(builder.asUint8Array()))

    // below code works with grpc native, but with grpc-js, errors printed:
    // INTERNAL: message.copy is not a function
    server.Authenticate(buffer, (err, response) => {
    })
```

### Environment
 - OS name, version and architecture: Ubuntu 20.04 amd64
 - Node version: v12.13.0
 - Node installation method: nvm
 - Package name and version: grpc-js - 1.5.10

**Comment by murgatroid99** [comment]
I think this is likely to be an error in the code generator. The object that ends up being `message` is the output of a `serialize` function, which is a function signature that returns a `Buffer` in both libraries. Since the `Buffer` class has a `copy` method, I can only assume that some other object made its way into that code path, and since the `serialize` function is provided by the code generator, that's where the problem probably is.

My guess is that, since neither library calls every method of the `Buffer` class, the FlatBuffer code generator was able to get away with providing some other object that happens to implement the subset of the `Buffer` API that the `grpc` library uses. But that is just coincidental compatibility.

**Comment by manhnt9** [comment]
Thank you, I'll try lowering the grpc-js version to see if it worked, or maybe upgrade the FlatBuffer to another version :+1:

**Comment by manhnt9** [comment]
If it won't work then we may be interested in doing a patch to have FlatBuffer compatibility. Could you spend some time giving us some instructions?

**Comment by manhnt9** [comment]
Yep, I should try upgrading to new FlatBuffers since I saw this line in its latest release: "Overhaul of TypeScript support."
Thanks !

Can be closed for now.
