### ISSUE TITLE
Channel credentials must be a ChannelCredentials object

### ISSUE THREAD

**Issue by thomakg** [grpc/grpc-node#2228]
### Problem description
After many hours of troubleshooting the interwebs, I have not yet found a solution to the problem of not matching types.
I have listed how I make proto files below, as well as what I have tried to fix it with so far.

As mentioned below I have two different node versions, but I don't see why that should be a problem?

### Environment
 - OS name, version and architecture: Mac M1
 - Node version 14 (when compiling proto files), Node version 16 for the consumer.
 - Node installation method nvm
 - If applicable, compiler version [e.g. clang 3.8.0-2ubuntu4]
 - Package name and version [e.g. gRPC@1.12.0]

### Additional context
This is the makefile script to create the proto files:
```
PROTOC_GEN_TS_PATH="./node_modules/.bin/protoc-gen-ts"
PROTOC_GEN_GRPC_PATH="./node_modules/.bin/grpc_tools_node_protoc_plugin"
TS_PROTOC="./node_modules/.bin/grpc_tools_node_protoc"
PROTOC_JS_FOLDER="./js"
protoc-js: js install-proto-tools
	$(TS_PROTOC) \
		-I proto \
		-I $(PROTOC_GEN_VALIDATE_PATH) \
		-I /usr/local/include \
        --plugin=protoc-gen-ts=${PROTOC_GEN_TS_PATH} \
        --plugin=protoc-gen-grpc=${PROTOC_GEN_GRPC_PATH} \
        --js_out=import_style=commonjs,binary:js \
        --ts_out="service=grpc-node,mode=grpc-js:${PROTOC_JS_FOLDER}" \
        --grpc_out="grpc_js:${PROTOC_JS_FOLDER}" \
		$(PROTO_FILES) $(VALIDATE_PROTO_FILES)
```

This is the error:
`TypeError: Channel credentials must be a ChannelCredentials object`

for the one compiling it, it is using version 1.7.0 of @grpc/grpc-js
For the one consuming it, it is using version 1.7.0 of @grpc/grpc-js

I've read that misaligned versions might be the reason, so I've update both to the same version.

Any help on the matter would be greatly appreciated!

**Comment by murgatroid99** [comment]
That error comes from constructing a `Channel` or `Client` object. Specifically, it indicates that the second parameter has the wrong type. The error that you are getting should tell you what code of yours is doing that operation. Please share that code, including the code that creates the object that ends up passed to that second parameter.

**Comment by thomakg** [comment]
Thanks for the fast reply, and sorry for the late response!

I've replicated it, keeping it as close to the original as possible in the following repo:
https://github.com/thomakg/grpc-node-test

I've tried with both fixing import script and without

**Comment by murgatroid99** [comment]
It looks like your package structure is forcing the generated code to use a different instance of the `@grpc/grpc-js` library than the application code is using, and that's probably causing the error. The Node import resolution algorithm walks up the directory tree until it finds a `node_modules` directory containing the requested package. Since you have the `@grpc/grpc-js` dependency declared in both the root `package.json` and `api/package.json`, both of those directories will have their own separate installation of the library. Then when you run the code, `api/src/world/index` will import from `api/node_modules` and `js/grpc/world/v1/world_grpc_pb` will import from `node_modules` at root.

**Comment by thomakg** [comment]
Hmmm so it might be because of npm link between? I can try to move the js folder into the api, that should hopefully resolve that?

It's kinda weird considering they use the same version, didn't know that types was that strict in TS.

**Comment by murgatroid99** [comment]
It's not *because* of npm link really, it's because you are using two instances of the same library. Different versions in the same dependency tree is one cause of that problem, but what you are doing is another. This is an `instanceof` check, which means that it checks the identity of the parent class. Two separately instantiated classes with the same definition don't count as the same class. This also has nothing to do with TypeScript, this is how JavaScript works.

**Comment by thomakg** [comment]
Ok, thanks for clarifying.
It seems to be working if I move it inside, which then resolves the problem highlighted above.

I've seen the same issue, even if the folder is not a sub-folder but rather a sibling, and then npm link between. 
That's why I suggested that it might be a link problem, if it defaults back to where it was linked from.

So I guess the easiest way to resolve this is to actually create the package then proper install it, that should remove that issue.
