### ISSUE TITLE
Channel credentials must be a ChannelCredentials object

### ISSUE THREAD

**Issue by nishiduka** [grpc/grpc-node#2411]
### Problem description
I'm trying to connect to gRPC server, but when I try to create an instance, it returns an error:

![image](https://user-images.githubusercontent.com/13911051/229891732-43d94ad2-6eed-48ad-af6e-7a9a4e3aa8ef.png)

### Reproduction steps
To reproduce, you can ran the code:
```js
const grpc = require('@grpc/grpc-js');
const service = require('foo/bar/service_grpc_pb');
const client = new service.serviceClient('localhost:50051', grpc.credentials.createInsecure());
```

### Environment
 - OS name, version and architecture: Linux Ubuntu 20.04 amd64
 - Node version: v18.15.0
 - Package name and version: @grpc/grpc-js@1.8.13

### Additional context
I'm trying to implement inside a nextjs application

**Comment by murgatroid99** [comment]
The most likely cause of this error is that your `foo/bar/service_grpc_pb` is using a different gRPC library than `@grpc/grpc-js`.

**Comment by tobiaskohlbau** [comment]
I had the same issue, caused by the cross using of ESM and CJS. That leads to [Dual CommonJS/ES module packages](https://nodejs.org/api/packages.html#dual-commonjses-module-packages). This has the result of _instanceof_ always failing to check if the the Credentials is of the right type.

I've locally forked grpc-js and created an ES module and now everything is working. Is there an particular reason grpc-js does not allow ESM and CJS combined? Otherwise I would like to send a PR to have grpc-js compatible with ESM and CJS.

The changes boil down to:

```
diff --git a/packages/grpc-js/package.json b/packages/grpc-js/package.json
index 815dabeb..3e2a5f69 100644
--- a/packages/grpc-js/package.json
+++ b/packages/grpc-js/package.json
@@ -4,7 +4,8 @@
   "description": "gRPC Library for Node - pure JS implementation",
   "homepage": "https://grpc.io/",
   "repository": "https://github.com/grpc/grpc-node/tree/master/packages/grpc-js",
-  "main": "build/src/index.js",
+  "main": "./build/commonjs/src/index.js",
+  "module": "./build/es2015/src/index.js",
   "engines": {
     "node": "^8.13.0 || >=10.10.0"
   },
@@ -45,7 +46,9 @@
   "scripts": {
     "build": "npm run compile",
     "clean": "rimraf ./build",
-    "compile": "tsc -p .",
+    "compile:cjs": "tsc -p . --outDir build/commonjs",
+    "compile:esm": "tsc -p . --module es2015 --outDir build/es2015 --moduleResolution node",
+    "compile": "npm run compile:cjs && npm run compile:esm",
     "format": "clang-format -i -style=\"{Language: JavaScript, BasedOnStyle: Google, ColumnLimit: 80}\" src/*.ts test/*.ts",
     "lint": "npm run check",
     "prepare": "npm run generate-types && npm run compile",
diff --git a/packages/grpc-js/src/index.ts b/packages/grpc-js/src/index.ts
index 51f39478..aa5ca9fc 100644
--- a/packages/grpc-js/src/index.ts
+++ b/packages/grpc-js/src/index.ts
@@ -278,7 +278,7 @@ import * as load_balancer_outlier_detection from './load-balancer-outlier-detect
 import * as channelz from './channelz';
 import { Deadline } from './deadline';
 
-const clientVersion = require('../../package.json').version;
+import { version as clientVersion } from '../package.json';
 
 (() => {
   logging.trace(LogVerbosity.DEBUG, 'index', 'Loading @grpc/grpc-js version ' + clientVersion);
diff --git a/packages/grpc-js/src/transport.ts b/packages/grpc-js/src/transport.ts
index 8abc13ab..7a19be9a 100644
--- a/packages/grpc-js/src/transport.ts
+++ b/packages/grpc-js/src/transport.ts
@@ -35,7 +35,7 @@ import { getNextCallNumber } from './call-number';
 const TRACER_NAME = 'transport';
 const FLOW_CONTROL_TRACER_NAME = 'transport_flowctrl';
 
-const clientVersion = require('../../package.json').version;
+import { version as clientVersion } from '../package.json';
 
 const {
   HTTP2_HEADER_AUTHORITY,
diff --git a/packages/grpc-js/test/test-retry-config.ts b/packages/grpc-js/test/test-retry-config.ts
index e27f236e..77b52d1c 100644
--- a/packages/grpc-js/test/test-retry-config.ts
+++ b/packages/grpc-js/test/test-retry-config.ts
@@ -15,7 +15,7 @@
  *
  */
 
-import assert = require("assert");
+import * as assert from 'assert';
 import { validateServiceConfig } from "../src/service-config";
 
 function createRetryServiceConfig(retryConfig: object): object {
```

**Comment by murgatroid99** [comment]
The "Dual package hazard" section in the documentation you linked seems to indicate that providing both options would actually make it more likely for people to encounter this problem. So, I definitely want to understand this situation better before applying that solution. Can you share a concrete example of code that experiences this issue with a single instance of the library?

**Comment by tobiaskohlbau** [comment]
> The "Dual package hazard" section in the documentation you linked seems to indicate that providing both options would actually make it more likely for people to encounter this problem. So, I definitely want to understand this situation better before applying that solution. Can you share a concrete example of code that experiences this issue with a single instance of the library?

Sure I will try to produce a reproduction repository. Maybe the TO could share his project too? Maybe both setups have valuable setups? In my case it was due to vite transpiling commonjs to esm. Any chance @nishiduka your project uses vite as well?

**Comment by 154pinkchairs** [comment]
The issue is probably with the way the latest revisions of libprotoc determine the global object. Namely:
```js
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();
```
 this works
 `var global = (function() { return this || window || global || self || Function('return this')(); }).call(null);`
 this (the new way of handling this) doesn't
 
 Here, `this` is null because of `.call(null)`, so it always falls back to checking the remaining options, unlike the previous solution, which checks the global object in a specific order and only falls back to `Function('return this')();` if all else fails, which should also return the global object in non-strict mode.
 
 Additionally, the use of `||` (logical OR) means that it will return the first truthy value it finds. But if `window`, `global`, and `self` are all undefined, it will not correctly default to the global object as intended. Instead, it may end up returning an incorrect value if, for example, window is a local variable that has a truthy value. The `||` operator does not check whether the values are defined, only whether they are truthy.
 
The new solution also doesn't check for `globalThis`, which is the recommended way to access the global object when available.

**Comment by nishiduka** [comment]
A aditional message: the protobuff compiled was transformed into a library.
In this case, I think is a problem with the peer dependecies.

When I remove the `@grpc/grpc-js` lib, the code worked!

Thanks guys!

**Comment by tobiaskohlbau** [comment]
I've found another Option to Workaround this. If using _vite_ try to set the `resolve.dedupe` Option. Like for e.g. in the following example used within an _SvelteKit_ application. The deduplication only transforms the CJS module once and therefore only one global scope exists.

```
import { sveltekit } from '@sveltejs/kit/vite';
import { defineConfig } from 'vitest/config';

export default defineConfig({
	plugins: [sveltekit()],
	test: {
		include: ['src/**/*.{test,spec}.{js,ts}']
	},
	resolve: {
		dedupe: ['@grpc/grpc-js']
	}
});
```

**Comment by dzivoing** [comment]
For me this worked import { ChannelCredentials } from 'google-gax';
