### ISSUE TITLE
Can you pls expose all grpc c++ channel option for the user to customise ?

### ISSUE THREAD

**Issue by Kiddinglife** [grpc/grpc-node#2418]
Hey, i cannot understand why the channel option grpc* are all hidden. I mean you should respect the end users’ needs. If you not understand those options, it’s fine. But why you hide all to the users? So weird. 

For example, the max idle connection timeout will cause stream remove error for steaming rpc. but I cannot set up using this library. Every option exist for some reasons for some specific cases. Pls show some respects. Thx.

**Comment by murgatroid99** [comment]
The deprecated `grpc` library provided all of those options because it was built on the same core library that the C++ library is built on. But `@grpc/grpc-js` is not built on that core library, so each one of those options is implemented separately in that library. All of the options that have been implemented are available for use.

We prioritize implementing options that we know users need, based on issues like this. So if there are any other options that you need that are not available yet, I suggest listing them here. I can't guarantee when we will get to that work, but pull requests are always welcome.

**Comment by murgatroid99** [comment]
The option `grpc.client_idle_timeout_ms` is available grpc-js 1.9.x.
