### ISSUE TITLE
Grpc client interceptors do not match proposal

### ISSUE THREAD

**Issue by artificial-aidan** [grpc/grpc-node#2486]
In [the proposal](https://github.com/grpc/proposal/blob/master/L5-node-client-interceptors.md) it has `message` arguments for `halfClose` and `cancel` interceptor functions, but looking at the code I only see `next` arguments for them. Was this an oversight or a technical issue?

Is there another way to get messages for those interceptors? I'm trying to catch errors and log them at the interceptor layer.

**Comment by artificial-aidan** [comment]
I still think there is a documentation issue here (or I'm missing something else) but I did manage to solve my problem.

```
const logInterceptor = (logger: any) => {
  return (options: any, nextCall: any) => {
    return new grpc.InterceptingCall(nextCall(options), {
      start: function (metadata, listener, next) {
        const logListener = {
          onReceiveStatus: function (status: grpc.StatusObject, next: any) {
            if (status.code !== grpc.status.OK) {
              logger.error(`adj: ${status.details}`);
            }
            next(status);
          },
        };
        next(metadata, logListener);
      },
    });
  };
};
```

**Comment by murgatroid99** [comment]
You are right that the `cancel` implementation deviated from the proposal. The proposal's `halfClose` definition doesn't have a `message` argument, so that one is the same.

Unfortunately, I don't see a way to make the `cancel` implementation conform to the proposal without breaking the current API, so I think we're just going to have to live with the discrepancy.

**Comment by artificial-aidan** [comment]
Thanks Michael
