### ISSUE TITLE
Upgrade `protobufjs` to fix security vulnerability `CVE-2023-36665`

### ISSUE THREAD

**Issue by luciomartinez** [grpc/grpc-node#2495]
### Problem description
`proto-loader` [requires](https://github.com/grpc/grpc-node/blob/1cc36e8df81c3972fb29a30aced678acee32680a/packages/proto-loader/package.json#L51) `protobufjs` with version `^7.0.0` with those version before `7.2.4` containing [CVE-2023-36665](https://www.tenable.com/cve/CVE-2023-36665)

### Additional context
https://www.tenable.com/cve/CVE-2023-36665

**Comment by murgatroid99** [comment]
The update has been published in `@grpc/proto-loader` version 0.7.8

**Comment by pachuka** [comment]
@luciomartinez @murgatroid99 - should `"@grpc/proto-loader": "^0.7.0",` also be updated in `packages/grpc-js/package.json` to `^0.7.8`? otherwise that can still resolve an older version of `protobufjs` right?:

![image](https://github.com/grpc/grpc-node/assets/3280602/0d4c36b3-8bf0-4f99-924c-b67b1ebbb83b)

**Comment by murgatroid99** [comment]
@pachuka The change you suggested has been published in grpc-js version 1.9.1

**Comment by pachuka** [comment]
@murgatroid99 Thank you, much appreciated!
