### ISSUE TITLE
google.protobuf.Struct not serializing properly

### ISSUE THREAD

**Issue by ElijahKSmith** [grpc/grpc-node#2500]
### Problem description

The `google.protobuf.Struct` type does not appear to be serializing/deserializing properly. The serializer appears to able to detect that it is a Struct based on the output received by the client containing the nested `fields` property, but the value is empty. Similarly on the client, the fields property is present in the deserialized data so it is possible it is not handling the type properly.

### Reproduction steps

[Minimal reproduction repo](https://github.com/ElijahKSmith/struct-grpc-repro), run instructions and expected/actual outcome included.

### Environment

 - OS name, version and architecture: Ubuntu 20.04.6 (on WSL 2 v1.2.5.0 on Windows 10.0.22621.1848)
 - Node version: 16.15.1
 - Node installation method: nvm
 - Package name and version: grpc-js 1.8.17, proto-loader 0.7.8

### Additional context

I attempted to call the method both from a client script and using Insomnia, both returned the same results. I would expect to see the serialized data in Insomnia and the deserialized data on the client, but both return the same data. It could therefore be possible that the deserializer on the client is also malfunctioning because it is not recognizing the response is a Struct and should be deserialized.

![image](https://github.com/grpc/grpc-node/assets/8062259/4e504b4c-3e3d-4a52-86a1-50a4fb42eb81)
![image](https://github.com/grpc/grpc-node/assets/8062259/4a8efaf7-bb05-455d-9c29-2017a4106e0e)

**Comment by murgatroid99** [comment]
The serializer does not automatically convert an arbitrary JSON object to the `Struct` message format type. You have to do that yourself. As you can see in [`struct.proto`](https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/struct.proto), the `Struct` message has a `fields` field, which has the type `map<string, Value>` and the `Value` message has a variety of fields in a `oneof` to handle different value types.

Fortunately, the algorithm to convert between JSON objects and `Struct` objects is relatively simple. For example, [here](https://github.com/grpc/grpc-node/blob/master/packages/grpc-js-xds/src/xds-bootstrap.ts#L161-L215) is one implementation in the `@grpc/grpc-js-xds` package.

---

For better or for worse, the serializer is relatively permissive in what objects it accepts, so the object you have is technically a valid input that serializes to the struct you see in that output. Specifically, you can always omit fields that are defined in messages, which causes them to take their default values, and the serializer does not process fields that are not defined in messages. Since your object does not have the `fields` field, the resulting serialized object has an empty map in that field.

**Comment by ElijahKSmith** [comment]
Thank you very much for your response, based on the code reference you provided I was able to implement a serializer/deserializer which appears to fix the issue (and have updated the reproduction repo with the examples for anyone that stumbles upon this issue in the future with the same question).

I do however have a followup question:

> The serializer does not automatically convert an arbitrary JSON object to the Struct message format type. You have to do that yourself.

Why is this the case? Does the serializer not have the context from the proto that the field is a `Struct`? And if it does, why does it not handle this?

**Comment by murgatroid99** [comment]
The proto-loader library uses protobuf.js for serialization and deserialization, and that library simply does not have general support for these "well known types" transformations. The transformations are in [this file](https://github.com/protobufjs/protobuf.js/blob/master/src/wrappers.js), and the only one currently implemented is `google.protobuf.Any`.

Unfortunately, `Struct` is particularly problematic, because it is so general. A valid `Struct` object is also a valid JSON object, so if that transformation is added now, it would break existing code that uses `Struct` messages.

**Comment by ElijahKSmith** [comment]
Got it, interesting that only one well-known type was implemented but I suppose that's up to the discretion of the `protobufjs` maintainers, hopefully for a future major version they'll consider it being that it's a breaking change. In the meantime I'll be creating a fork/patch for my own needs.

Thank you for your help!
