### ISSUE TITLE
[@grpc/reflection] Can only add one proto file to server

### ISSUE THREAD

**Issue by gawsoftpl** [grpc/grpc-node#2630]
### Is your feature request related to a problem? Please describe.
For package @grpc/reflection user can only add one proto file to reflection server. 

Perfect solution is add array of protoLoaders file
```js
const reflection = new ReflectionService([protoLoaders.apidata, protoLoaders.health]);
reflection.addToServer(server);
```

**Comment by murgatroid99** [comment]
A `ReflectionService` object is constructed from a loaded package definition object. That package definition object can be created using multiple proto files, so that is a way to reflect services from multiple proto files. However, multiple package definitions cannot be used due to compatibility issues described in [the "Open Issues" section of the design](https://github.com/grpc/proposal/blob/master/L108-node-grpc-reflection-library.md#user-is-restricted-to-loading-a-single-packagedefinition).
