### ISSUE TITLE
successful calls still emit 'cancelled' as of v1.10.x

### ISSUE THREAD

**Issue by davidfiala** [grpc/grpc-node#2771]
I was working on adding v1.10.x support to the https://github.com/deeplay-io/nice-grpc repos.

As lightly documented in https://github.com/deeplay-io/nice-grpc/issues/555#issuecomment-2148456515 I believe I discovered that server call handlers emit 'cancelled' even on successful RPCs. The v1.9.x series does not appear to do this. It appears to have been introduced behavior in the `server-interceptor.ts` file in 1.10.0 merge.

Is the behavior of always emitting call cancelled an explicit intention? Or a possible bug?

Thanks for your time.

**Comment by murgatroid99** [comment]
Yes, that was intentional.

From my point of view, the primary purpose of the `cancelled` signal is to notify the handler and any interceptors that no more processing is needed, and any resources associated with the call can be discarded, when they might otherwise not know that. Previously, that would only happen because of network events or calling `Server#forceShutdown`, but now it can also happen if a server interceptor ends a call on its own. As a result, the simplest way to ensure that the handler always gets that notification is to emit the `cancelled` event if the call ends in any way.
