### ISSUE TITLE
Travis-CI Build Configuration

### ISSUE THREAD

**Issue by ChrisCates** [grpc/grpc-node#325]
Hey,

Noticed one of the travis-ci builds failed.
It was on version 10.

9 wasn't tested either... But I'm sure it will work with the latest copy.

Any specific reason as to why this fails? Happy to look into it.

Also, any specific reason for using `--depth=50` in travis? Why not just use `--depth=1`.

**Comment by nicolasnoble** [comment]
We're actually not using Travis anymore, due to the volume of tests we're doing. I should disable / delete its settings files and configuration. Tests are currently happening on Kokoro, Google's deployment of Jenkins. You can see the result of the tests on each pull request.

Also, due to a problem with nodejs 10 itself, it wasn't possible to run nodejs 10 tests, but since there is a 10.1.0 release since today, it may have incorporated the fix.

**Comment by ChrisCates** [comment]
Thanks for the heads up!

I'll see what's happening on the Node.js repo and see if things are getting resolved on their end.
I always prefer the latest copy :)

**Comment by ChrisCates** [comment]
Oh and make sure to put a link (or badge) to the Kokoro tests on the readme.
Thanks!
