### ISSUE TITLE
Denial of service advisory

### ISSUE THREAD

**Issue by sidhuko** [grpc/grpc-node#327]
We're currently having issues with our security checks using the gprc-node packages. The package `grpc-native-core` contains an old version of protobufjs which should be updated to 6.8.4.

https://nodesecurity.io/advisories/605

I've started a patch but its a major version increment so a few breaks in tests.

**Comment by murgatroid99** [comment]
We are not going to upgrade that package's dependency to Protobuf.js 6 because it would be a breaking change. As an alternative solution, I have submitted a patch to Protobuf.js 5 [here](https://github.com/dcodeIO/protobuf.js/pull/1030) to fix this problem within the same major version. When that gets published, we will upgrade our dependency to it.

**Comment by nicolasnoble** [comment]
Duplicate of https://github.com/grpc/grpc-node/issues/277, waiting for a protobufjs release.
