### ISSUE TITLE
I am using firebase/firestore as my backend and i encounter this issue with GRPCClient

### ISSUE THREAD

**Issue by lioneltan** [grpc/grpc-node#424]
dyld: Library not loaded: @rpath/GRPCClient.framework/GRPCClient
  Referenced from: /Users/lionel/Library/Developer/CoreSimulator/Devices/E356F442-BF86-42D0-8973-E9BE725F99BA/data/Containers/Bundle/Application/14C59412-B712-41D8-8F2A-3865027FC83A/vivisell.app/vivisell
  Reason: image not found
(lldb) 
<img width="1014" alt="screen shot 2018-07-09 at 12 50 16 am" src="https://user-images.githubusercontent.com/29434929/42422092-da3b7446-8312-11e8-98c9-e9cc48f9e593.png">

**Comment by nicolasnoble** [comment]
Issue isn't following our [issue template](https://github.com/grpc/grpc-node/issues/new?template=bug_report.md), and as mentioned in it, no reproduction steps means the issue is closed immediately. Please re-open a new issue following our [issue template](https://github.com/grpc/grpc-node/issues/new?template=bug_report.md), and file all of the required fields.

**Comment by nicolasnoble** [comment]
Also, very likely this has nothing to do with grpc-node...

**Comment by murgatroid99** [comment]
To expand on that, this appears to be the Objective C library. For problems with that library you should file an issue at https://github.com/grpc/grpc.
