### ISSUE TITLE
How to access a Message and use google.protobuf.Any

### ISSUE THREAD

**Issue by psaelango** [grpc/grpc-node#430]
> ProtoFile - gateway.proto
```
import "google/protobuf/timestamp.proto";
package test.io.gateway;

service Gateway
{
  rpc UserLogin (UserLoginCmd) returns (UserLoginRsp) {}
}
message UserLoginCmd
{
    string username= 1;
    string password = 2;
}
message UserLoginRsp
{
    string accesstoken= 1;
}
message Something
{
    google.protobuf.Any data = 1;
}
```
> Javascript File - some.js
```
PROTO_PATH = "C:\\Users\\firstname.lastname\\Documents\\io\\gateway.proto";
protoDefinition = protoLoader.loadSync(PROTO_PATH,{
    keepCase: true,
    longs: String,
    enums: String,
    defaults: true,
    oneofs: true
  });
proto = grpc.loadPackageDefinition(protoDefinition).test.io.gateway;
console.log(proto); //Has only service (Gateway) 
```
The above code runs fine and prints only the service. But I want access the message (Something) to achieve this - https://github.com/google/protobuf/issues/2612.

Please kindly help me here to understand the way to access the message and google.protobuf.Any.

Thanks in advance.

@murgatroid99  - Can you please kindly share your thoughts. Also I couldn't able to use includeDirs properly. 
```
PROTO_PATH = "C:\\Users\\firstname.lastname\\Documents\\io\\gateway.proto";
protoDefinition = protoLoader.loadSync(PROTO_PATH,{
    keepCase: true,
    longs: String,
    enums: String,
    defaults: true,
    oneofs: true,
    includeDirs: ["C:\\Users\\firstname.lastname\\Documents\\io\\*.proto"]
  });
proto = grpc.loadPackageDefinition(protoDefinition).test.io.gateway; // Get error - io of undefined
```
The above code crashes & gives error `io of undefined`

**Comment by murgatroid99** [comment]
First of all, the `@grpc/proto-loader` package is intended to be used for loading service definitions in `.proto` files for use with other grpc libraries. In your `.proto` file, you do not use the `Something` message type in a service, so you should not expect to be able to access it using the proto loader library.

Second, you seem to be saying that you want to use the solution in the issue you linked to. That issue is about the package `google-protobuf`, so you should use that package. If your goal is to use a `google.protobuf.Any` object with `@grpc/proto-loader`, you are going to have some difficulty. That package does not have any special support for the `Any` type, so you will have to explicitly use a protobuf implementation to serialize and deserialize the binary blob in the object.

Third, the `includeDirs` option has to be a list of directory names. The value you passed is not a directory name but a glob, which is not valid there.

**Comment by psaelango** [comment]
@murgatroid99  - My apologies. `Something` message is an example for  google.protobuf.Any. But I couldn't able to access UserLoginCmd as well. So can you please tell how to access `UserLoginCmd ` message. Also for `includeDirs` - I have tried `"C:\\Users\\firstname.lastname\\Documents\\io"` which didn't work

**Comment by nicolasnoble** [comment]
You don't access the messages using `@grpc/proto-loader`. That's not its purpose.

**Comment by psaelango** [comment]
@murgatroid99  @nicolasnoble  - Can you guys please give an example implementation of `google.protobuf.Any` for javascript.
```
list = new test.io.Something(); // What goes here?
any = new google.protobuf.Any();
any.pack(list.serializeBinary(), ‘test.io.Something’);
```
This is what I've tried so far

**Comment by nicolasnoble** [comment]
I'm not familiar with google.protobuf.Any, and you're asking questions about protobuf's API, not grpc's. I'm not properly equipped to answer this.

**Comment by murgatroid99** [comment]
If you are using the `google-protobuf` library, you should follow along with the issue you linked in the original post. If you are using `@grpc/proto-loader`, that library does not have any special handling for `google.protobuf.Any`, and I would suggest looking at https://github.com/dcodeIO/protobuf.js to figure out how to manually handle it. Either way, this question does not really seem to be about grpc, so I am closing it.
