### ISSUE TITLE
reply err code 14

### ISSUE THREAD

**Issue by daishenghao** [grpc/grpc-node#440]
### Problem description
When there are no request to GRPC service for a while, the request to the GRPC service will reply err

### Reproduction steps
1. start GRPC service
2. start client to connect GRPC service,  request  and response is correct
3. keep no request for a while (about 15minutes ) , then send a request, it will reply err
the err is : {code: 14, details: "TCP Read failed", metadata { _internal_repr: {} }
4. then send a request again, the reponse is working regularly

### Environment
 - win10 x64
 - NodeJS v8.9.4
 - npm install grpc
 - gRPC@1.13.0

**Comment by nicolasnoble** [comment]
This is working as intended. Error 14 is "unavailable", and is meant to be retried by the caller. What you're describing is normal behavior.

**Comment by murgatroid99** [comment]
To add to what @nicolasnoble said, what is probably happening here is that the connection is getting dropped by the kernel while it is idle, and gRPC detects that when it tries to make a new request. That request fails, but gRPC then automatically reconnects, which is why the following request succeeds. That is part of the reason that we recommend retrying when the status is UNAVAILABLE.

**Comment by nicolasnoble** [comment]
You don't check the connection itself manually. You simply have to care with the error codes sent to you by the API.

If you send a call, and you get `grpc.status.UNAVAILABLE`, you simply have to retry exactly the same call. That's really all there is to it.

**Comment by daishenghao** [comment]
@nicolasnoble I got it。 Thank you for taking the time to answer my question.
