### ISSUE TITLE
Determine if the bundled dependency on node-pre-gyp can be removed in 2.0

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc-node#56]
For the grpc 2.0 package, we plan to drop support for Node 4, 5, and 7. At the same time, we may be able to easily change the minimum version of npm we require. When we do so, we should re-evaluate whether the original reasons for bundling the dependency on node-pre-gyp still apply.

As grpc/grpc#12798 demonstrates, there are some risks involved in pinning the version of the dependency by bundling it.

**Comment by murgatroid99** [comment]
This isn't really relevant anymore.

**Comment by cprussin** [comment]
@murgatroid99 so the bundled dependency actually does cause a problem for packages that use yarn, as yarn [does not really support bundled dependencies properly](https://github.com/yarnpkg/yarn/issues/3751).  In my case, this results in `error "grpc#tar#safe-buffer" is wrong version: expected "5.1.2", got "5.1.1"` on `yarn check` (unfortunately I can't paste in the relevant package.json as it's a private project; I have not yet been able to reproduce with a minimal example).  While I think yarn is working on properly supporting bunldedDependencies, I'm also curious if there's any value to grpc by using a bundled dep here?  Can this be revisited?

**Comment by nicolasnoble** [comment]
@cprussin we really aren't supporting yarn officially to distribute grpc-node.

**Comment by cprussin** [comment]
Fair enough, but I'm curious if grpc even gets anything out of this distribution scheme? If not, seems like a harmless enough change to make it at least functional no?

**Comment by nicolasnoble** [comment]
It's more a matter of having the resources, knowledge and testing capabilities to support everything, really. Maybe there's a way to handle distributing the package differently, but we have a method that now works, and we're not necessarily keen on researching something new just to support all the edge cases - which then might break another previously working workflow.

As for the bundled dependencies, it really is the method recommended by node-pre-gyp to be distributed. Due to its nature, having npm deduping package will break it. See https://github.com/mapbox/node-pre-gyp/issues/61 for more details about this.

**Comment by cprussin** [comment]
Got it, that's helpful information. Thank you!
