### ISSUE TITLE
“Error: 14 UNAVAILABLE: TCP Write failed” with hyperledger Fabric blockchain application

### ISSUE THREAD

**Issue by Bagoos** [grpc/grpc-node#893]
I am actually working with this Hyperledger Fabric blockchain application on my computer (https://github.com/rastringer/medication-blockchain) and I can run the application on port 8000.

But I have a problem: when I want to create drug record or change drug holder with the application on port 8000, I have this message in my terminal:

"... Transaction proposal was good 
Successfully sent Proposal and received ProposalResponse: Status - 200, message - "" 
Failed to invoke successfully :: Error: There was a problem with the eventhub ::Error: 14 UNAVAILABLE: TCP Write failed"

And sometimes I have the same message but with:

..."TCP Read failed"

More, the green message with the success of the transaction and the transaction ID is not writing like the example in the picture, and this for the both (create drug record & change drug holder).

But when I refresh the page on the port 8000, the new transaction appears in the table, even if there is the message error.

And I checked the application in another computer, and there is not this problem (I have the last version of Linux Ubuntu 18.04.2)

Somebody told me it's probably a problem with the GRPC, or a problem with the person code who build this app (maybe he changed some code on hyperledger fabric pre existing code to adapt his app)

Thank you in advance for any help :)

**Comment by murgatroid99** [comment]
Those messages mean that the underlying network connection is breaking for some reason before the entire request and response is complete. That can happen after the server gets the request and starts processing it, so it's not surprising that you will sometimes see that the request was handled by the server even when you get this error on the client.

This error is reported by gRPC, but it's not really caused by gRPC. You will need some other way of figuring out why you are having these network problems.

**Comment by Bagoos** [comment]
A solution of this problem is here -> https://pastebin.com/Z8FdM7e9

Basically you have to change to the app 2 fonctions (changer_holer & add_drug) inside "controller.js" file.
